name: Post Merge Action

on:
  pull_request:
    types:
      - closed
    paths:
      - ".github/workflows/post-merge-action.yml"

jobs:
  print_labels:
    name: Print PR labels (only for PRs merged into main with the acceptance label)
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && !contains(github.event.pull_request.labels.*.name, 'skip_acceptance')
    runs-on: ubuntu-latest
    steps:
      - name: Print PR labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          echo "This PR was merged into ${{ github.event.pull_request.base.ref }} and contained the following labels:"
          echo $LABELS
