name: Post Merge Action

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && contains(github.event.pull_request.labels.*.name, 'acceptance')
    runs-on: ubuntu-latest
    steps:
      - name: Print PR labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
        run: |
          echo "This PR was merged into ${{ github.event.pull_request.base.ref }} and contained the following labels:"
          echo $LABELS
