name: Publish Docs (push)

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  # Give the GITHUB_TOKEN write permission to commit and push the
  # changes made to switcher.json.
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.PAT }}

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: python -m pip install -e . --no-deps --force-reinstall

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        pushd docs
        make clean html linkcheck
        popd

    - name: Update switcher and latest version
      if: ${{ github.event_name == 'release' }}
      run: |
        python docs/update_switcher.py --version ${{ github.ref_name }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: ${{ github.event_name == 'release' }}
      with:
        commit_message: Update switcher.json to ${{ github.ref_name }}
        branch: ${{ github.head_ref }}

    - name: Publish to Github Pages on main
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        destination_dir: dev
        keep_files: false

    - name: Publish to Github Pages on release
      if: ${{ github.event_name == 'release' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        destination_dir: ${{ github.ref_name }}
