name: sandbox
on: [push]
jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v6

      - name: Install Nextmv CLI
        uses: nextmv-io/setup-nextmv@v1
        with:
          api-key: ${{ secrets.NEXTMV_API_KEY }}

      - name: Push new version of nextroute and update staging instance
        run: |
          nextmv cloud app push -a nextroute --version-yes --update-instance-id staging
        working-directory: ./nextroute
