name: sandbox
on: [push]
jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: Install Nextmv CLI
        uses: nextmv-io/setup-nextmv@v1
        with:
          api-key: ${{ secrets.NEXTMV_API_KEY }}

      - name: Clone a community app for test purposes
        run: |
          git clone https://github.com/nextmv-io/community-apps.git

      - name: Do something with CLI
        run: |
          nextmv cloud app push -a nextroute --version-yes --update-instance-id staging
          nextmv cloud run create -a nextroute -i input.json --wait
        working-directory: ./community-apps/go-nextroute
